<a href="https://colab.research.google.com/github/HarshrajRay/Collage-assignment-Foundation-of-Data-Science/blob/main/NumoyKA_Istemal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

---



In [ ]:
import numpy as np
import pandas as pd
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
print(np.__version__)

1.25.2


**Now let's make dimensional array**

---




**0 D Array**

In [ ]:
import numpy as np
arr = np.array(42)
print(arr)

42


**1 D Array**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


**2 D Array**

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**3 D Array**

In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,2,3]],[[1,2,3],[5,6,7],[3,4,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 2 3]]

 [[1 2 3]
  [5 6 7]
  [3 4 6]]]


**Sclicing**

---



In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1:2,0:3])

[[6 7 8]]


---
---
**EXERCISE PROBLEM**
---




In [ ]:
#Question 1
import numpy as np
print(np.__version__)

1.25.2


In [ ]:
#Question 2
import numpy as np

x = np.array([1,2,3,4,5])

print("Original array:")
print(x,"\n")

print("Does array have a zero as elemet:")
print(np.all(x),"\n")

x = np.array([0,2,3,4])
print("Changed array")
print(x,"\n")
print("Does array have a zero as element:")
print(np.all(x))

Original array:
[1 2 3 4 5] 

Does array have a zero as elemet:
True 

Changed array
[0 2 3 4] 

Does array have a zero as element:
False


In [ ]:
#Question 3
import numpy as np

i = np.array([1,2,3,4,5])
j = np.array([6,7,8,9,10])

print("Original arrays")

print(i)
print(j,"\n")

print("Greater")
print(np.greater(i,j),"\n")

print("Greater and Equal")
print(np.greater_equal(i,j),"\n")

print("Less")
print(np.less(i,j),"\n")

print("Less and Equal")
print(np.less_equal(i,j))


Original arrays
[1 2 3 4 5]
[ 6  7  8  9 10] 

Greater
[False False False False False] 

Greater and Equal
[False False False False False] 

Less
[ True  True  True  True  True] 

Less and Equal
[ True  True  True  True  True]


In [ ]:
#Question 4
import numpy as np

arr = np.array([1, 7, 13, 105])

print("Original array:")
print(X)

print("Size of the memory occupied by the said array:")
print( (arr.size * arr.itemsize),"bytes")

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes


In [ ]:
#Question 5
import numpy as np
arr = np.arange(30,71)
print("Array of elements from 30 to 70:")
print(arr)

Array of elements from 30 to 70:
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
#Question 6
import numpy as np
arr = np.arange(30,71,2)
print("Array of even elements from 30 to 70:")
print(arr)

Array of even elements from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#Question 7
import numpy as np
arr = np.identity(3)
print("3x3 Martrix \n")
print(arr)

3x3 Martrix 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Sample code
import numpy as np
a = np.arange(11,23).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
Each element of the array is:
11 12 13 14 15 16 17 18 19 20 21 22 